static const char * BuiltIn[] = {
      "^Cosine",
      "^Avg",
      "^Count",
      "^Max",
      "^Min",
      "^Multiply",
      "^Sum",
      "^Transpose",
      "^IDF",
      "^TermCorrelate",
      "^DocCorrelate",
      "^Sim1",
      "^Dice",
      "^Jaccard",
      "^Centroid",
      "^Scan",
      "^ScanAlnum",
      "^Input",
      "" };
